<#
.SYNOPSIS
    Signs one or more files (exe / dll / msi / msix / appx) with
    signtool.exe.

.DESCRIPTION
    Wrapper on signtool.exe using SHA256 + RFC 3161 timestamp.
    Supports two modes:
      1) Certificate in the Windows store: pass
         -CertificateThumbprint
      2) .pfx file: pass -CertificatePath + -CertificatePassword

    The timestamp is MANDATORY: without it, the signature expires
    with the certificate (and Windows rejects it). The default
    timestamp server is DigiCert's free endpoint; can be overridden
    via -TimestampUrl.

.PARAMETER Files
    One or more file paths to sign (wildcards supported).

.PARAMETER CertificateThumbprint
    Thumbprint (SHA-1, no spaces) of the certificate in
    Cert:\CurrentUser\My or Cert:\LocalMachine\My.

.PARAMETER CertificatePath
    Path to the .pfx file.

.PARAMETER CertificatePassword
    SecureString with the .pfx password.

.PARAMETER TimestampUrl
    RFC 3161 timestamp server URL. Default:
    http://timestamp.digicert.com

.PARAMETER Description
    Description shown in the UAC / SmartScreen dialog. Default:
    MedReminder.

.PARAMETER SignToolPath
    Path to signtool.exe. If omitted, searches PATH and the typical
    Windows SDK locations (10.0.22621.0, 10.0.26100.0).

.EXAMPLE
    # Sign with the self-signed generated by make-selfsigned-cert.ps1
    .\sign-artifact.ps1 -Files dist\*.msi -CertificateThumbprint ABC123...

.EXAMPLE
    # CI signing with .pfx (environment variable for the password)
    $pwd = ConvertTo-SecureString $env:SIGN_PFX_PASSWORD -AsPlainText -Force
    .\sign-artifact.ps1 -Files dist\MedReminder-1.0.1-x64.msix `
        -CertificatePath cert.pfx -CertificatePassword $pwd

.NOTES
    Verify after signing with:
      signtool.exe verify /pa /v <file>
    It must show "Successfully verified" and include a line
    "The signature is timestamped".
#>
[CmdletBinding(DefaultParameterSetName = 'Thumbprint')]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string[]]$Files,

    [Parameter(Mandatory = $true, ParameterSetName = 'Thumbprint')]
    [string]$CertificateThumbprint,

    [Parameter(Mandatory = $true, ParameterSetName = 'Pfx')]
    [string]$CertificatePath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Pfx')]
    [SecureString]$CertificatePassword,

    [string]$TimestampUrl = "http://timestamp.digicert.com",
    [string]$Description = "MedReminder",
    [string]$SignToolPath
)

$ErrorActionPreference = 'Stop'

function Find-SignTool {
    param([string]$Explicit)
    if ($Explicit) {
        if (Test-Path $Explicit) { return $Explicit }
        throw "SignTool not found at path: $Explicit"
    }
    $cmd = Get-Command signtool.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }

    $candidates = @(
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.26100.0\x64\signtool.exe",
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe",
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.22000.0\x64\signtool.exe",
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe"
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { return $c }
    }
    throw "signtool.exe not found. Install the Windows SDK or pass -SignToolPath."
}

$signtool = Find-SignTool -Explicit $SignToolPath
Write-Host "SignTool: $signtool" -ForegroundColor Cyan
Write-Host "Timestamp: $TimestampUrl" -ForegroundColor Cyan

$resolvedFiles = @()
foreach ($pattern in $Files) {
    $matches = Get-ChildItem -Path $pattern -File -ErrorAction SilentlyContinue
    if (-not $matches) {
        Write-Warning "No file found for: $pattern"
        continue
    }
    $resolvedFiles += $matches.FullName
}

if ($resolvedFiles.Count -eq 0) {
    throw "No file to sign."
}

# Build the signtool arguments
$args = @(
    'sign',
    '/fd', 'SHA256',
    '/td', 'SHA256',
    '/tr', $TimestampUrl,
    '/d', $Description,
    '/v'
)

if ($PSCmdlet.ParameterSetName -eq 'Thumbprint') {
    # signtool looks in CurrentUser\My by default; if the cert is
    # in LocalMachine\My, add /sm as an extra signtool argument.
    Write-Host "Signing with in-store certificate, thumbprint: $CertificateThumbprint" -ForegroundColor Cyan
    $args += @('/sha1', $CertificateThumbprint)
}
else {
    Write-Host "Signing with .pfx: $CertificatePath" -ForegroundColor Cyan
    if (-not (Test-Path $CertificatePath)) {
        throw "PFX not found: $CertificatePath"
    }
    $plainPwd = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($CertificatePassword))
    $args += @('/f', $CertificatePath, '/p', $plainPwd)
}

$args += $resolvedFiles

Write-Host ""
Write-Host "Signing in progress ($($resolvedFiles.Count) files)..." -ForegroundColor Yellow
& $signtool @args
if ($LASTEXITCODE -ne 0) {
    throw "signtool sign failed with exit code $LASTEXITCODE"
}

Write-Host ""
Write-Host "Verifying signature..." -ForegroundColor Yellow
foreach ($f in $resolvedFiles) {
    Write-Host ""
    Write-Host "  $f" -ForegroundColor White
    & $signtool verify /pa /v $f
    if ($LASTEXITCODE -ne 0) {
        throw "Signature verification failed for: $f"
    }
}

Write-Host ""
Write-Host "OK — all files signed and verified." -ForegroundColor Green
