using System.IO.Compression;
using System.Text;
using FluentAssertions;
using MedReminder.Domain.Catalogue;
using MedReminder.Infrastructure.Catalogue.Parsers;
using Xunit;

namespace MedReminder.Infrastructure.Tests.Catalogue;

// Exercises the AEMPS / CIMA parser against the 142-row curated
// fixture under tests/fixtures/catalogue/aemps-cima-sample.xlsx.
//
// The fixture is generated by openpyxl (see docs/CATALOGUE-DATA.md
// §4.3), which writes cell values as inline strings (t="inlineStr").
// The real CIMA export uses shared strings (t="s"); a dedicated test
// builds a mini shared-strings workbook in memory so both code paths
// are covered by CI, not just the inline one.
public sealed class AempsCimaParserTests
{
    private static readonly CountryCode Spain = CountryCode.Parse("ES");

    [Fact]
    public async Task Parses_every_data_row_and_records_no_skips_on_the_curated_fixture()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();

        var rows = await CollectAsync(parser, report);

        rows.Should().HaveCount(142);
        report.Skipped.Should().Be(0);
    }

    [Fact]
    public async Task Every_yielded_row_carries_country_ES()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();

        var rows = await CollectAsync(parser, report);

        rows.Should().OnlyContain(r => r.Country == Spain);
        rows.Should().OnlyContain(r => r.Country.Value == "ES");
    }

    [Fact]
    public void SupportedCountries_lists_ES_only()
    {
        var parser = new AempsCimaParser();

        parser.SupportedCountries.Should().ContainSingle().Which.Value.Should().Be("ES");
    }

    [Fact]
    public async Task National_code_uses_the_Numero_Registro_verbatim_and_is_unique()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();
        var rows = await CollectAsync(parser, report);

        rows.Select(r => r.NationalCode).Should().OnlyHaveUniqueItems();
        rows.Should().OnlyContain(r => r.NationalCode.Length >= 5);
    }

    [Fact]
    public async Task Marketing_status_covers_the_three_CIMA_states()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();
        var rows = await CollectAsync(parser, report);

        var statuses = rows.Select(r => r.MarketingStatus).Where(s => s is not null).Distinct().ToList();
        statuses.Should().Contain("Autorizado");
        statuses.Should().Contain("Anulado");
        statuses.Should().Contain("Suspenso");
    }

    [Fact]
    public async Task Multi_ingredient_row_splits_active_substance_on_comma_space()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();
        var rows = await CollectAsync(parser, report);

        // Any row whose "Nº P. Activos" was >= 2 must reach the row
        // stream with two or more ingredients. Every substance in the
        // resulting row must be non-empty and distinct.
        var multi = rows.Where(r => r.ActiveIngredients.Count >= 2).ToList();
        multi.Should().NotBeEmpty(
            "the fixture is stratified to include multi-ingredient rows");
        multi.Should().OnlyContain(r => r.ActiveIngredients.All(i => !string.IsNullOrWhiteSpace(i.Name)));
        multi.Should().OnlyContain(r =>
            r.ActiveIngredients.Select(i => i.Name).Distinct(StringComparer.OrdinalIgnoreCase).Count()
                == r.ActiveIngredients.Count);
    }

    [Fact]
    public async Task Row_level_ATC_is_copied_onto_every_ingredient_of_the_row()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();
        var rows = await CollectAsync(parser, report);

        // AEMPS ships an ATC per medicinal product, not per substance.
        // The parser copies it onto every ingredient (same convention
        // as AifaSnapshotParser). Verify that every multi-ingredient
        // row has the same ATC on all its ingredients — or all null,
        // for the (rare) rows the XLSX exports without ATC.
        foreach (var row in rows.Where(r => r.ActiveIngredients.Count >= 2))
        {
            var atcs = row.ActiveIngredients.Select(i => i.Atc).Distinct().ToList();
            atcs.Should().ContainSingle($"row {row.NationalCode} must carry the same ATC on all ingredients");
        }
    }

    [Fact]
    public async Task Observaciones_lands_on_DispensingRegime_when_present()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();
        var rows = await CollectAsync(parser, report);

        // The fixture has rows across the four regime buckets AEMPS
        // exports (prescription / hospital / diagnostic / biológicos).
        // At least one must reach DispensingRegime.
        rows.Any(r => r.DispensingRegime is not null
                && r.DispensingRegime.Contains("Prescripción", StringComparison.Ordinal))
            .Should().BeTrue();
    }

    [Fact]
    public async Task PharmaceuticalForm_and_Dosage_and_links_are_always_null()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();
        var rows = await CollectAsync(parser, report);

        // AEMPS XLSX embeds form + dose inside CommercialName, and
        // does not expose leaflet / SPC URLs as structured columns.
        // The parser leaves the four fields null — same shape as
        // EPAR's PharmaceuticalForm / Dosage nulls.
        rows.Should().OnlyContain(r =>
            r.PharmaceuticalForm == null
            && r.Dosage == null
            && r.LinkLeaflet == null
            && r.LinkSpc == null);
    }

    [Fact]
    public async Task Parser_reads_from_a_non_seekable_stream()
    {
        var parser = new AempsCimaParser();
        var report = new ParseReport();

        await using var seekable = CatalogueFixtures.BuildAempsSnapshotStream();
        await using var nonSeekable = new NonSeekableStreamWrapper(seekable);

        var rows = new List<ReferenceMedicineRow>();
        await foreach (var row in parser.ParseAsync(nonSeekable, report, CancellationToken.None))
        {
            rows.Add(row);
        }

        rows.Should().HaveCount(142);
    }

    [Fact]
    public async Task Shared_string_cell_type_is_resolved_via_the_sharedStrings_table()
    {
        // Build a mini XLSX in memory that uses t="s" (the shape the
        // real Medicamentos.xls emits) instead of the t="inlineStr"
        // shape openpyxl produces. Both code paths must land on the
        // same ReferenceMedicineRow schema, or the parser silently
        // returns empty commercial names against the real AEMPS
        // snapshot.
        var xlsxBytes = BuildSharedStringWorkbook();
        var outerBuffer = new MemoryStream();
        using (var outerZip = new ZipArchive(outerBuffer, ZipArchiveMode.Create, leaveOpen: true))
        {
            var entry = outerZip.CreateEntry("aemps.xlsx", CompressionLevel.NoCompression);
            using var s = entry.Open();
            s.Write(xlsxBytes, 0, xlsxBytes.Length);
        }
        outerBuffer.Position = 0;

        var parser = new AempsCimaParser();
        var report = new ParseReport();

        var rows = new List<ReferenceMedicineRow>();
        await foreach (var row in parser.ParseAsync(outerBuffer, report, CancellationToken.None))
        {
            rows.Add(row);
        }

        rows.Should().HaveCount(1);
        var only = rows[0];
        only.NationalCode.Should().Be("SS-001");
        only.CommercialName.Should().Be("SHARED STRING MEDICAMENTO");
        only.MarketingAuthorisationHolder.Should().Be("Lab Compartido S.A.");
        only.MarketingStatus.Should().Be("Autorizado");
        only.DispensingRegime.Should().Be("Uso Hospitalario");
        only.ActiveIngredients.Should().HaveCount(2);
        only.ActiveIngredients.Select(i => i.Name).Should().Equal("SUBSTANCIA A", "SUBSTANCIA B");
        only.ActiveIngredients.Should().OnlyContain(i => i.Atc == null || i.Atc.Value.Value == "N02BE01");
    }

    private static byte[] BuildSharedStringWorkbook()
    {
        // A minimal-but-valid OOXML workbook: one worksheet, one
        // header row + one data row, all cell values pointing into
        // xl/sharedStrings.xml except the "Nº P. Activos" numeric
        // column. Only the parts the parser reads are populated
        // (workbook.xml, sheet1.xml, sharedStrings.xml,
        // [Content_Types].xml, _rels — the two rels files the format
        // requires for the package to open at all).
        var shared = new[]
        {
            "Nº Registro",              // 0
            "Medicamento",               // 1
            "Laboratorio",               // 2
            "Fecha Aut.",                // 3
            "Estado",                    // 4
            "Fecha Estado",              // 5
            "Cód. ATC",                 // 6
            "Principios Activos",        // 7
            "Nº P. Activos",             // 8
            "¿Comercializado?",          // 9
            "¿Triangulo Amarillo?",      // 10
            "Observaciones",             // 11
            "¿Sustituible?",             // 12
            "¿Afecta conducción?",       // 13
            "¿Problemas de suministro?", // 14
            "SS-001",                    // 15
            "SHARED STRING MEDICAMENTO", // 16
            "Lab Compartido S.A.",       // 17
            "01/01/2024",                // 18
            "Autorizado",                // 19
            "02/01/2024",                // 20
            "N02BE01",                   // 21
            "SUBSTANCIA A, SUBSTANCIA B",// 22
            "SI",                        // 23
            "NO",                        // 24
            "Uso Hospitalario",          // 25
        };

        var sst = new StringBuilder();
        sst.Append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>");
        sst.Append("<sst xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" count=\"")
           .Append(shared.Length).Append("\" uniqueCount=\"").Append(shared.Length).Append("\">");
        foreach (var s in shared)
        {
            sst.Append("<si><t>").Append(System.Security.SecurityElement.Escape(s)).Append("</t></si>");
        }
        sst.Append("</sst>");

        // Sheet1 with two rows. Every cell uses t="s" + <v>index</v>
        // except I2 which is numeric (t="n"). Headers use A1..O1 and
        // data uses A2..O2 (column M2 is intentionally left absent,
        // matching how real spreadsheets omit blanks — the parser
        // must still read the surrounding cells correctly).
        var sheet = new StringBuilder();
        sheet.Append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>");
        sheet.Append("<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">");
        sheet.Append("<sheetData>");
        sheet.Append("<row r=\"1\">");
        for (int i = 0; i < 15; i++)
        {
            sheet.Append("<c r=\"").Append(ColumnLetter(i)).Append("1\" t=\"s\"><v>").Append(i).Append("</v></c>");
        }
        sheet.Append("</row>");
        // Data row: shared indices 15..25 are the values (M2 omitted).
        int idx = 15;
        sheet.Append("<row r=\"2\">");
        for (int col = 0; col < 15; col++)
        {
            if (col == 8) // "Nº P. Activos" — numeric
            {
                sheet.Append("<c r=\"").Append(ColumnLetter(col)).Append("2\" t=\"n\"><v>2</v></c>");
                continue;
            }
            if (col == 12) // "¿Sustituible?" — deliberately absent
            {
                continue;
            }
            sheet.Append("<c r=\"").Append(ColumnLetter(col)).Append("2\" t=\"s\"><v>").Append(idx++).Append("</v></c>");
        }
        sheet.Append("</row>");
        sheet.Append("</sheetData></worksheet>");

        var workbook =
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
            "<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" " +
                     "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">" +
            "<sheets><sheet name=\"Hoja1\" sheetId=\"1\" r:id=\"rId1\"/></sheets>" +
            "</workbook>";

        var contentTypes =
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
            "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
            "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
            "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
            "<Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>" +
            "<Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>" +
            "<Override PartName=\"/xl/sharedStrings.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml\"/>" +
            "</Types>";

        var rootRels =
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
            "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
            "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/>" +
            "</Relationships>";

        var xlRels =
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
            "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
            "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>" +
            "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings\" Target=\"sharedStrings.xml\"/>" +
            "</Relationships>";

        var buffer = new MemoryStream();
        using (var zip = new ZipArchive(buffer, ZipArchiveMode.Create, leaveOpen: true))
        {
            AddText(zip, "[Content_Types].xml", contentTypes);
            AddText(zip, "_rels/.rels", rootRels);
            AddText(zip, "xl/_rels/workbook.xml.rels", xlRels);
            AddText(zip, "xl/workbook.xml", workbook);
            AddText(zip, "xl/sharedStrings.xml", sst.ToString());
            AddText(zip, "xl/worksheets/sheet1.xml", sheet.ToString());
        }
        return buffer.ToArray();
    }

    private static void AddText(ZipArchive zip, string path, string content)
    {
        var entry = zip.CreateEntry(path, CompressionLevel.NoCompression);
        using var s = entry.Open();
        var bytes = Encoding.UTF8.GetBytes(content);
        s.Write(bytes, 0, bytes.Length);
    }

    private static string ColumnLetter(int columnIndex)
    {
        // 0-based → "A".."Z" (only 15 columns needed here).
        return ((char)('A' + columnIndex)).ToString();
    }

    private static async Task<List<ReferenceMedicineRow>> CollectAsync(
        AempsCimaParser parser, ParseReport report)
    {
        var rows = new List<ReferenceMedicineRow>();
        await using var snapshot = CatalogueFixtures.BuildAempsSnapshotStream();
        await foreach (var row in parser.ParseAsync(snapshot, report, CancellationToken.None))
        {
            rows.Add(row);
        }
        return rows;
    }

    private sealed class NonSeekableStreamWrapper : Stream
    {
        private readonly Stream _inner;

        public NonSeekableStreamWrapper(Stream inner) => _inner = inner;

        public override bool CanRead => true;
        public override bool CanSeek => false;
        public override bool CanWrite => false;
        public override long Length => throw new NotSupportedException();
        public override long Position
        {
            get => throw new NotSupportedException();
            set => throw new NotSupportedException();
        }

        public override int Read(byte[] buffer, int offset, int count)
            => _inner.Read(buffer, offset, count);

        public override void Flush() { }
        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
        public override void SetLength(long value) => throw new NotSupportedException();
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
    }
}
