name: Download AIFA CSV

on:
  schedule:
    - cron: '0 3 2 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Generate files
        run: |
          python scarica_aifa.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/

          git diff --staged --quiet || git commit -m "AIFA database update $(date +%Y%m)"

          git push